#!/bin/bash

THIS_DIR=$(cd -- $(dirname "$BASH_SOURCE"); pwd)

export PS1=$(echo "$PS1" | sed 's/^\['"$CLOUDSDK_ACTIVE_CONFIG_NAME"'\] //')

if gcloud config configurations list --format='value(name)' | grep -q "^$CLOUDSDK_ACTIVE_CONFIG_NAME$"
then
    save_gcloud_conf

    CLOUDSDK_DEACTIVATED_CONFIG_NAME="$CLOUDSDK_ACTIVE_CONFIG_NAME"
    export CLOUDSDK_ACTIVE_CONFIG_NAME="$CLOUDSDK_PREVIOUS_CONFIG_NAME"

	gcloud config configurations delete --quiet "$CLOUDSDK_DEACTIVATED_CONFIG_NAME"

fi

export PATH=$(echo ":$PATH:" | sed 's#:'"$THIS_DIR"'[^:]*#:#g; s#^::*##; s#::*$##')
export PYTHONPATH=$(echo ":$PYTHONPATH:" | sed 's#:'"$THIS_DIR"'[^:]*#:#g; s#^::*##; s#::*$##')

unset CLOUDSDK_PREVIOUS_CONFIG_NAME CLOUDSDK_DEACTIVATED_CONFIG_NAME THIS_DIR
unalias save_gcloud_conf
