#!/bin/bash

THIS_DIR=$(cd -- $(dirname "$BASH_SOURCE"); pwd)

if gcloud config configurations list --format='value(name)' | grep -q "^$CLOUDSDK_ACTIVE_CONFIG_NAME$"
then
    cp -f "$HOME/.config/gcloud/configurations/config_$CLOUDSDK_ACTIVE_CONFIG_NAME" "$GCLOUD_CONF_FILE"

    CLOUDSDK_DEACTIVATED_CONFIG_NAME="$CLOUDSDK_ACTIVE_CONFIG_NAME"
    export CLOUDSDK_ACTIVE_CONFIG_NAME="$CLOUDSDK_PREVIOUS_CONFIG_NAME"

	gcloud config configurations delete --quiet "$CLOUDSDK_DEACTIVATED_CONFIG_NAME"

    unset CLOUDSDK_PREVIOUS_CONFIG_NAME CLOUDSDK_DEACTIVATED_CONFIG_NAME
fi

export PATH=$(echo ":$PATH:" | sed 's#:'"$THIS_DIR"'[^:]*#:#g; s#^::*##; s#::*$##')
